before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/gcore-cli
    binary: gcore-cli
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -extldflags=-static
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64

archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - '^Merge'

release:
  github:
    owner: g-core
    name: gcore-cli

brews:
  - name: gcore-cli
    commit_author:
      name: goreleaserbot
      email: goreleaserbot@gcore.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    homepage: "https://github.com/G-Core/gcore-cli"
    description: "The official Gcore CLI"
    license: "Apache-2.0"
    skip_upload: auto
    repository:
      owner: G-Core
      name: homebrew-tap
      # see https://goreleaser.com/errors/resource-not-accessible-by-integration
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
