before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/gcore-cli
    binary: gcore-cli
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -extldflags=-static
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64

archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - '^Merge'

release:
  github:
    owner: g-core
    name: gcore-cli
