name: FOSSA

on:
  push:
    branches: [ 'main' ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ 'main' ]

jobs:
  fossa:
    runs-on: ubuntu-latest

    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install FOSSA CLI
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash

      - name: Run FOSSA Analysis
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_PUB_API_KEY }}
        run: fossa analyze

      - name: Run FOSSA Test
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_PUB_API_KEY }}
        run: fossa test
